### ISSUE TITLE
Color of cells are wrong for independent runs

### ISSUE THREAD

**Issue by VaninJoel** [CompuCell3D/CompuCell3D#728]
There is a problem with previously defined cell`s color for independent runs on HPC. CC3D is grabbing the information for coloring cells from the **_settings.sqlite** file and not from the **screenshots.json** This is a problem when you are trying to tie the screenshots for different models or if there is no **_settings.sqlite** file, the colors are defined from the default CC3D and not from the **screenshots.json**

**Comment by VaninJoel** [comment]
Scratch that I tried using the _settings.sqlite file to see if the colors would be maintained but that also did not work.

**Comment by VaninJoel** [comment]
So we are working on the headless Tatooine env, and we even tried to change the **_settings.xml** and **_settingsosx.xml** from both from core and player5 folders since the colors I was seeing the default colors present in those files, by rewriting the Hex colors for the cell types there, but none of them seems had an effect on the color of cells using both the API caller or the .sh call.

**Comment by fyffep** [comment]
Can you please attach the relevant files, screenshots.json,  _settings.sqlite, and _settings.xml ?
We may not need any of them to resolve the bug, but it could still help.

**Comment by VaninJoel** [comment]
[FilesConfig.zip](https://github.com/user-attachments/files/15744411/FilesConfig.zip)
These are the files that I directly substituted directly on CC3D running on my environment, and there was no change in the color scheme
![Cell_Field_CellField_2D_XY_0_000000](https://github.com/CompuCell3D/CompuCell3D/assets/34976329/6a15c362-2b14-431f-96ea-3c28f21982ed)

**Comment by VaninJoel** [comment]
BTW, the weird thing is that other things from the screenshot data, like the size of the window, have been pulled correctly.

**Comment by maciekswat** [comment]
this should be fixed in the most recent PR

**Comment by VaninJoel** [comment]
I ran the new PR(cc3d_4_6) not fixed. It still does not correctly get the cell colors:
![Cell_Field_CellField_2D_XY_0_000000](https://github.com/CompuCell3D/CompuCell3D/assets/34976329/155d2b9d-20fb-43fb-9db4-b8dc9cfd997a)

**Comment by VaninJoel** [comment]
IDK, one thing that I noticed is that these colors are the ones described in the original _settings.xml and _settingsosx.xml for cell types: <Settings Type="dict">
      <e Name="TypeColorMap" Type="dict">
         <e Name="0" Type="color">#000000</e>
         <e Name="1" Type="color">#00ff00</e>
         <e Name="10" Type="color">#ffffff</e>
         <e Name="2" Type="color">#0000ff</e>
         <e Name="3" Type="color">#ff0000</e>
         <e Name="4" Type="color">#808000</e>
         <e Name="5" Type="color">#c0c0c0</e>
         <e Name="6" Type="color">#ff00ff</e>
         <e Name="7" Type="color">#000080</e>
         <e Name="8" Type="color">#00ffff</e>
         <e Name="9" Type="color">#008000</e>
      </e>

**Comment by maciekswat** [comment]
how do you run the simulation. I tested it using Player and it worked fine. Do you use run_script? If so I may need to test it separately

**Comment by maciekswat** [comment]
I ran run_script the way you would run it on the HPC cluster with a generated screenshot file that takes multiple screenshot configurations. When I was generating screenshots I changed the colors of the cell type to test if different screenshots will be produced each one with different colors. And it does exactly what expected - we gen several screenshots for each MCS each one with different cell type colors which shows that the colors are being read directly from ``screenshot_data/screenshots.json``
<img width="1386" alt="image" src="https://github.com/CompuCell3D/CompuCell3D/assets/5384661/d860627d-a8fe-4e0e-a7e0-f72dce9bcd09">
the command I used was 

```commandline
python -m cc3d.run_script --input <prefix>/ExtraFields/ExtraFields.cc3d -f 100 --log-level DEBUG --log-to-file -fs 100
```

when you replace ``prefix`` with path pointing to ``ExtraFields/ExtraFields.cc3d`` 

I am attaching the simulation I ran along with the screenshots
[ExtraFields.tar.gz](https://github.com/user-attachments/files/15781404/ExtraFields.tar.gz)

**Comment by VaninJoel** [comment]
So here is what is funny on the local machine when we call it through run_script, API, or player all of them work. The problem is seems to be when I involve Xvfb here is how I call it for both version 4.5 and 4.6 just changing the env name there: 
xvfb-run -a srun \
{base_path}.conda/envs/cc3d_450_310/bin/cc3d_runScript.sh -i {cc3d_file}

**Comment by VaninJoel** [comment]
@maciekswat Is there any command to save just the .vtk file from Python?

**Comment by maciekswat** [comment]
```commandline
python -m cc3d.run_script -i <path to .cc3d> -f 100
```

this will output vtk snapshots every 100

**Comment by VaninJoel** [comment]
I thought I could get around using the VTK data and get the images only of the simulations that I want and run it locally for the cell colors. However, some fields, like any tracked field, do not come with the VTK file. So, I am going to do a dirty fix and try to find where the standard colors are being defined. I tried a couple of different places, as mentioned before _settings.xml and _settingsosx.xml from both from core and player5 folders and none of them worked. Do you have any suggestions for other places where the standard colors are being set?

**Comment by maciekswat** [comment]
@VaninJoel did we fix it or is it still an issue?
